theme: jekyll-theme-minimal
title: Jonathan Vercoutre
description: Senior Site Reliability Engineer based in Lille, France 🇫🇷
logo: /images/profile.jpg
url: https://jonathan.vercout.re

plugins:
  - jekyll-sitemap
  - jekyll-seo-tag
